try{
   console.log("hello")
   console.log(a)
   console.log("try-end")
}
catch{
   console.log("err handled")
}
finally{
   console.assertlog("finally")
}

console.log("handled")